server:
  port: 8080

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888

cloud:
  gateway:
    discovery:
      locator:
        enabled: true
    routes:
      - id: user
        uri: http://localhost:8090