server:
  port: 8080

spring:
  application:
    name: gateway

cloud:
  gateway:
    discovery:
      locator:
        enabled: true
    routes:
      - id: user
        uri: http://localhost:8090

eureka:
  client:
    register-with-eureka: false